

services:
  bernabei-tracker:
    image: ghcr.io/alphios72/bernabei:latest
    container_name: bernabei-tracker
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/bernabei.db
      - TZ=Europe/Rome
      - SCRAPER_DELAY_MIN=1
      - SCRAPER_DELAY_MAX=5
      - SCRAPER_PROXY=http://elbdzkgg:8smav65siz70@45.38.107.97:6014 # Format: http://user:pass@host:port
