version: '3.8'

services:
  bernabei-tracker:
    image: ghcr.io/alphios72/bernabei:latest
    container_name: bernabei-tracker
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/bernabei.db
      - TZ=Europe/Rome
